#ifndef _JOYSTICK_H_
#define _JOYSTICK_H_

enum _joystick_event_t {
	JOYSTICK_UNKNOWN,
	JOYSTICK_AXIS_UP,
	JOYSTICK_AXIS_DOWN,
	JOYSTICK_AXIS_LEFT,
	JOYSTICK_AXIS_RIGHT,
	JOYSTICK_AXIS_CENTER,
	JOYSTICK_BUTTON_PRESSED,
	JOYSTICK_BUTTON_RELEASED,
};
typedef enum _joystick_event_t joystick_event_t;

static const char *joystick_event_name[] = {
	"JOYSTICK_UNKNOWN",
	"JOYSTICK_AXIS_UP",
	"JOYSTICK_AXIS_DOWN",
	"JOYSTICK_AXIS_LEFT",
	"JOYSTICK_AXIS_RIGHT",
	"JOYSTICK_BUTTON_PRESSED",
	"JOYSTICK_BUTTON_RELEASED",
};

#endif // _JOYSTICK_H_
